var search={
  "ArchaeologicalSite Instances Collection": "http://leiza-scit.github.io/CAA2026-alligator/ArchaeologicalSite_collection",
  "Arretine Dated Sites Collection": "http://leiza-scit.github.io/CAA2026-alligator/collections/arretine_sites",
  "Asberg, Lager": "http://leiza-scit.github.io/CAA2026-alligator/DEaJQL",
  "Asberg, Lagerdorf": "http://leiza-scit.github.io/CAA2026-alligator/Q93OlW",
  "Augsburg, Stadt": "http://leiza-scit.github.io/CAA2026-alligator/zggRNd",
  "Augsburg-Oberhausen": "http://leiza-scit.github.io/CAA2026-alligator/M8BAmk",
  "Augst, Insula 20": "http://leiza-scit.github.io/CAA2026-alligator/vJnM0D",
  "Augst, Insula 31": "http://leiza-scit.github.io/CAA2026-alligator/rR3Mgy",
  "Augst, Theater": "http://leiza-scit.github.io/CAA2026-alligator/p4zxM0",
  "Avenches, Insula 15": "http://leiza-scit.github.io/CAA2026-alligator/rY6gGz",
  "Bad Nauheim": "http://leiza-scit.github.io/CAA2026-alligator/kBRoVE",
  "Basel, Lager": "http://leiza-scit.github.io/CAA2026-alligator/W4XmgP",
  "Basel, Lagerdorf": "http://leiza-scit.github.io/CAA2026-alligator/qJE4nZ",
  "Bonn, Boeselagerhof": "http://leiza-scit.github.io/CAA2026-alligator/oQZq80",
  "Braives": "http://leiza-scit.github.io/CAA2026-alligator/BWKpDQ",
  "Bregenz": "http://leiza-scit.github.io/CAA2026-alligator/zLjX82",
  "Clades Variana": "http://leiza-scit.github.io/CAA2026-alligator/event_Clades_Variana",
  "Conimbriga": "http://leiza-scit.github.io/CAA2026-alligator/Ndnd3r",
  "Dangstetten": "http://leiza-scit.github.io/CAA2026-alligator/MADy9p",
  "Drusus campaigns": "http://leiza-scit.github.io/CAA2026-alligator/event_Drusus_campaigns",
  "E53_Place Instances Collection": "http://leiza-scit.github.io/CAA2026-alligator/E53_Place_collection",
  "E7_Activity Instances Collection": "http://leiza-scit.github.io/CAA2026-alligator/E7_Activity_collection",
  "FeatureCollection Instances Collection": "http://leiza-scit.github.io/CAA2026-alligator/FeatureCollection_collection",
  "Friedberg": "http://leiza-scit.github.io/CAA2026-alligator/LmM3V1",
  "Germanicus campaigns": "http://leiza-scit.github.io/CAA2026-alligator/event_Germanicus_campaigns",
  "Haltern": "http://leiza-scit.github.io/CAA2026-alligator/vXGN59",
  "Instant Instances Collection": "http://leiza-scit.github.io/CAA2026-alligator/Instant_collection",
  "Interval Instances Collection": "http://leiza-scit.github.io/CAA2026-alligator/Interval_collection",
  "Lausanne-Vidy": "http://leiza-scit.github.io/CAA2026-alligator/gdWKYL",
  "Liberchies": "http://leiza-scit.github.io/CAA2026-alligator/QXlWK2",
  "LineString Instances Collection": "http://leiza-scit.github.io/CAA2026-alligator/LineString_collection",
  "Lorenzberg": "http://leiza-scit.github.io/CAA2026-alligator/Ee4KvG",
  "Maastricht": "http://leiza-scit.github.io/CAA2026-alligator/JmWOrl",
  "Mainz, Legionslager": "http://leiza-scit.github.io/CAA2026-alligator/Repn5M",
  "Namur": "http://leiza-scit.github.io/CAA2026-alligator/LJA4XN",
  "Neuss": "http://leiza-scit.github.io/CAA2026-alligator/OljG8l",
  "Nijmegen, Lager (Brunsting)": "http://leiza-scit.github.io/CAA2026-alligator/jm48qv",
  "Nijmegen, Lager (Haalebos)": "http://leiza-scit.github.io/CAA2026-alligator/vd0j5N",
  "Nijmegen, Trajanusplein": "http://leiza-scit.github.io/CAA2026-alligator/NedG0W",
  "Nijmegen, Valkhof": "http://leiza-scit.github.io/CAA2026-alligator/Krj7Qq",
  "Oberaden": "http://leiza-scit.github.io/CAA2026-alligator/rJXxA7",
  "Oberwinterthur, R\u00f6merstr. 186": "http://leiza-scit.github.io/CAA2026-alligator/mkGlqM",
  "Period cluster 11 BCE \u2013 8 CE": "http://leiza-scit.github.io/CAA2026-alligator/collections/cluster_bc0011_ad0008",
  "Period cluster 12 BCE \u2013 8 CE": "http://leiza-scit.github.io/CAA2026-alligator/collections/cluster_bc0012_ad0008",
  "Period cluster 15 BCE \u2013 9 BCE": "http://leiza-scit.github.io/CAA2026-alligator/collections/cluster_bc0015_bc0009",
  "Period cluster 16 BCE \u2013 13 CE": "http://leiza-scit.github.io/CAA2026-alligator/collections/cluster_bc0016_ad0013",
  "Period cluster 16 BCE \u2013 8 CE": "http://leiza-scit.github.io/CAA2026-alligator/collections/cluster_bc0016_ad0008",
  "Period cluster 16 BCE \u2013 9 BCE": "http://leiza-scit.github.io/CAA2026-alligator/collections/cluster_bc0016_bc0009",
  "Period cluster 16 BCE \u2013 9 CE": "http://leiza-scit.github.io/CAA2026-alligator/collections/cluster_bc0016_ad0009",
  "Period cluster 16 \u2013 28 CE": "http://leiza-scit.github.io/CAA2026-alligator/collections/cluster_ad0016_ad0028",
  "Period cluster 7 BCE \u2013 9 CE": "http://leiza-scit.github.io/CAA2026-alligator/collections/cluster_bc0007_ad0009",
  "Period cluster 7 \u2013 13 CE": "http://leiza-scit.github.io/CAA2026-alligator/collections/cluster_ad0007_ad0013",
  "PeriodCluster Instances Collection": "http://leiza-scit.github.io/CAA2026-alligator/PeriodCluster_collection",
  "Place Instances Collection": "http://leiza-scit.github.io/CAA2026-alligator/Place_collection",
  "Point Instances Collection": "http://leiza-scit.github.io/CAA2026-alligator/Point_collection",
  "Polygon Instances Collection": "http://leiza-scit.github.io/CAA2026-alligator/Polygon_collection",
  "R\u00f6dgen": "http://leiza-scit.github.io/CAA2026-alligator/B95OZz",
  "Site Instances Collection": "http://leiza-scit.github.io/CAA2026-alligator/Site_collection",
  "Tiberian campaign": "http://leiza-scit.github.io/CAA2026-alligator/event_Tiberian_campaign",
  "Titelberg": "http://leiza-scit.github.io/CAA2026-alligator/J3R6nX",
  "Tongeren": "http://leiza-scit.github.io/CAA2026-alligator/oqJAd8",
  "Trier-Petrisberg": "http://leiza-scit.github.io/CAA2026-alligator/site_Trier-Petrisberg",
  "Vechten": "http://leiza-scit.github.io/CAA2026-alligator/KmaGQd",
  "Velsen": "http://leiza-scit.github.io/CAA2026-alligator/EOD041",
  "Vetera I": "http://leiza-scit.github.io/CAA2026-alligator/KbRY6O",
  "Vindonissa, K\u00f6nigsfelden": "http://leiza-scit.github.io/CAA2026-alligator/b0OGdE",
  "Vindonissa, Milit\u00e4rstation": "http://leiza-scit.github.io/CAA2026-alligator/N5ZEJo",
  "Vindonissa, Scheuerhof": "http://leiza-scit.github.io/CAA2026-alligator/N5MVXe",
  "Wiesbaden": "http://leiza-scit.github.io/CAA2026-alligator/RjmPA4",
  "Worms": "http://leiza-scit.github.io/CAA2026-alligator/Qz2oRe",
  "Zurzach, Lager": "http://leiza-scit.github.io/CAA2026-alligator/xbEdvL",
  "Z\u00fcrich, Lindenhof": "http://leiza-scit.github.io/CAA2026-alligator/ojlAy1",
  "event Instances Collection": "http://leiza-scit.github.io/CAA2026-alligator/event_collection"
}